'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SquareTank.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property coilheateroff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coilheateroff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coilheateron1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coilheateron1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stirrer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stirrer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer141() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer141", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stirrer9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stirrer9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
